cmv/cmv-app

viewer/js/gis/dijit/Find.js

use the .dgrid-row:click to handle zooming to clicked feature.  This handles the case where the user has clicked on a feature, then manually panned the map.  Now clicking on the selected feature will pan the map back to the selected feature.

zoom on row click instead of select

---

viewer/js/config/viewer.js
viewer/js/viewer/Controller.js

Add support for hiding operational layers in the legend (legendLayerInfo...s array).  Adds an optional property to the layer options parameter in the operational layers config section of viewer.js which when false will prevent the layer from being added to the legendLayerInfos array.

add support for hiding operational layers in the legend 

---

viewer/js/gis/dijit/LayerControl.js
viewer/js/gis/dijit/LayerControl/controls/ImageVector.js
viewer/js/gis/dijit/LayerControl/controls/Raster.js
viewer/js/gis/dijit/LayerControl/controls/Stream.js
viewer/js/gis/dijit/LayerControl/controls/WebTiled.js
viewer/js/viewer/Controller.js

Add support for the following layer types to CMV Controller and the layerControl widget:
* WebTiledLayer
* ArcGISImageServiceVectorLayer (with legend)
* RasterLayer
* StreamLayer (with Legend)
Add support for the following layer types to Controller:
* DataAdaptorFeatureLayer (untested)

Add support for additional layer types

---

viewer/js/gis/dijit/Identify.js

This is an edit of the pull request [here](https://github.com/cmv/cmv-app/pull/416). Check for a content value in the popup identify config and if it exists, call the setContent method on the popup after initializing it.
The `InfoTemplate` class has a setContent method which is inherited by the `PopupInfo` class. This method allows the user to set a custom function which can return widgets and custom html formatting. See [Format info window](https://developers.arcgis.com/javascript/jshelp/intro_formatinfowindow.html)

Allow the use of the popup's setContent method.

---

viewer/js/gis/dijit/LayerControl.js
viewer/js/gis/dijit/LayerControl/controls/_DynamicSublayer.js
viewer/js/gis/dijit/LayerControl/css/LayerControl.css

Just wanted to start a discussion on adding extensible menus to the sublayers in the layer control, starting with the dynamic type. 
I set this up so a user would pass a subLayerMenu option to the layercontroller and add menu items to each control by type. This property could be overridden by the `layerControlLayerInfos` property on the layer.
```JavaScript
subLayerMenu: {
dynamic: [{
label: 'Query Layer...',
iconClass: 'fa fa-search fa-fw',
topic: 'queryLayer'
}, {
label: 'Open Attribute Table',
topic: 'openTable',
iconClass: 'fa fa-table fa-fw'
}]
},
```
On the menu click, the layer controller publishes a topic, `'LayerControl/topicName'` which passes the layer and the subLayer to any widgets subscribed to that topic.

Add menu to Layer Controller sub-layers

---

viewer/js/gis/dijit/Geocoder.js

CMV Geocoder option `mapExtentSearch: true` sets `arcgisGeocoder.searchExtent` to map extent when widget loads and on 'extent-change'.

limit geocoder search to map extent

---

viewer/js/gis/dijit/MapInfo.js

Added check for non-numeric scale. Closes #381

avoid occasional error in `number.format` in mapInfo widget

---

viewer/js/config/viewer.js
viewer/js/gis/dijit/LayerControl/controls/_DynamicFolder.js
viewer/js/gis/dijit/LayerControl/controls/_DynamicSublayer.js
viewer/js/gis/dijit/LayerControl/css/LayerControl.css

This array determines which sublayer and folder controls are visible.
The visibility of the actual sublayers is not affected.
Also includes `layerIds` array in imageParameters to demonstrate how to
set the initial visibility of sublayers.

Added new `layerIds` option to layerControl configuration.

---

.eslintrc
viewer/js/viewer/_MapMixin.js

the method.
This is useful when using CMV with BootstrapMap
(https://github.com/Esri/bootstrap-map-js).

Add new `_createMap` method to allow custom mixins to override

---

viewer/js/gis/dijit/LayerControl.js
viewer/js/gis/dijit/LayerControl/controls/_DynamicFolder.js
viewer/js/gis/dijit/LayerControl/controls/_DynamicSublayer.js
viewer/js/gis/dijit/LayerControl/plugins/legendUtil.js

//add new layer
function _setupSampleLayer(args) {
var layer = args.layer;
var target = args.target;
layer.setVisibility(true);
layer.opacity = 1;
for (var i = 0; i < 8; i++) {
var eLayerInfo = layer.layerInfos[i];
eLayerInfo.defaultVisibility = true
}
};
function _loadSampleLayer() {
var imageParameters = new esri.layers.ImageParameters();
imageParameters.layerIds = [0,1,2,3,4,5,6,7];
imageParameters.layerOption =
esri.layers.ImageParameters.LAYER_OPTION_SHOW;
var layer = new
esri.layers.ArcGISDynamicMapServiceLayer("http://<server>/arcgis/rest/services/<service>/MapServer",
{id: "MyMapService",
visible : true,
imageParameters : imageParameters
}
);
layer.on("load", function(args) {
_setupSampleLayer(args);
});
layer.on("error", function(args) {
debugger;
}); …

Added support to add & remove layer(s) from the Layer Control

---

viewer/js/config/identify.js

After looking through CMV docs, it seemed most appropriate to just put
this property here.  The sample config object in the docs is for
viewer.js or custom info windows and this is a pretty straightforward
setting.

Added 'draggable' property to identify config object

---

viewer/js/gis/dijit/Basemaps.js

We can change the basemap with events
dojo.publish('basemaps/updateBasemap',['gray'])

Update the basemap via publish

---

viewer/js/config/viewer.js
viewer/js/gis/dijit/LayerControl.js
viewer/js/gis/dijit/LayerControl/controls/Dynamic.js
viewer/js/gis/dijit/LayerControl/controls/_DynamicFolder.js
viewer/js/gis/dijit/LayerControl/controls/_DynamicSublayer.js
viewer/js/viewer/_MapMixin.js

These changes allow the user to have granular control over each subLayer
in a dynamic Map service.  Now, instead of having to just use the name
of the layer in the map, you can override it to whatever you'd like.
you can also redefine the min/max scale of the subLayer.
see the layerInfo properties defined here:
https://developers.arcgis.com/javascript/jsapi/layerinfo-amd.html
In addition to the subLayerInfo support, i've added two other properties
to the layerControlLayerInfos object.
1) subLayerInfos : array of layerInfos that should override the dynamic
map service's default layerInfos
2) excludedLayers : an array of layer ids that should not be exposed in
the map service
3) includeUnspecifiedLayers: boolean --> if true, then all layers in the
dynamic map service will be added, not just …

Sub layer support

---

viewer/js/gis/dijit/LayerControl/controls/_Control.js

The scaleRangeHandler was being tracked outside of the _handlers list.
In some scenarios this handler would never be released.  This fix
confirms that this handler is tracked for a final destroy

Track Scale Range Handler for final destroy()

---

viewer/js/viewer/_LayoutMixin.js
viewer/js/viewer/_MapMixin.js

this was introduced when Controller was split into separate mixins.

including panes config in viewer.js breaks application.

---

viewer/js/gis/dijit/Help.js
viewer/js/gis/dijit/Help/nls/pt-pt/resource.js
viewer/js/gis/dijit/Help/nls/resource.js
viewer/js/gis/dijit/Help/templates/HelpDialog.html

This is an addition to the PR #572. The Help widget was missing.
- Remove widget title from its main source file (it was already defined in config/viewer.js)
- add i18n to the link in the top right corner of the cmv-app main screen
- add i18n to the tabs titles and all content
- includes Portuguese translation (PT-PT)

add nls support to the help widget

---

viewer/js/gis/dijit/Identify.js

- when group layers are not visible, but child layers are, child layers are still identified
- should fix https://github.com/cmv/cmv-app/issues/367 and https://github.com/cmv/cmv-app/issues/601
Should probably test this a bit

Fix sublayer visibility issue

---

viewer/js/viewer/_LayoutMixin.js

Allow initially-hidden non-collapsible panes, sanitize togglePane 'show' parameter, and publish a subscribable event when toggling a pane. This allows for better declarative configuration without needing to utilize CSS properties or javascript callbacks.
Note : setting "open: false" still causes the sidebar to flash before disappearing. This is because the initial CSS is still set to display 'block'. To fix this, the pane initialization function would need to modify the CSS of the sidebar before it is rendered.

Update pane initialization and display logic

---

viewer/js/gis/dijit/FloatingTitlePane.js

dojo included with ESRI JS API 3.17+ adds detection for MS Edge browser so
we can use that as a more reliable approach to solving the original issue #379
with dragging floating windows in Internet Explorer and Edge browsers.

remove use of our own (unreliable) drag delay for floating windows

---

viewer/js/viewer/_LayoutMixin.js

Panes are not toggleable by the button since https://github.com/cmv/cmv-app/pull/607

Fix broken pane toggle

---

viewer/js/gis/dijit/Identify.js

The id may not be the same as the index to the layerInfos array

Identify widget - account for hard-coded sublayer IDs in checkVisibilityRecursive

---

viewer/js/gis/dijit/FloatingTitlePane.js

With Chrome version 55 (in the Chrome beta and dev channels), a floating titlePane widget does not stop dragging when the mouse is released. This is the same behavior previously experienced in IE 11 and MS Edge. Version 55 is expected to be released to the Chrome stable channel on [December 6th](https://www.chromium.org/developers/calendar).
I believe the issue is related to this [dojo bug](https://bugs.dojotoolkit.org/ticket/17314). Based on that report, this PR overrides the `onMouseUp` in dojo Mover class. The fix has been tested with the effected browser versions as well as Firefox.

Fix titlePane issue effecting IE 11/M.S. Edge and now Chrome v 55

---

viewer/js/config/basemaps.js
viewer/js/config/nls/es/main.js
viewer/js/config/nls/fr/main.js
viewer/js/config/nls/main.js
viewer/js/config/nls/pt-br/main.js
viewer/js/config/nls/pt-pt/main.js
viewer/js/gis/dijit/Basemaps.js

basemap `mode` is no longer required.
also includes support for all parameters available in the Basemap Gallery widget.
removed i18n for esri basemap to use the esri title. Title can be changed in config.

basemap widget - support custom and agol basemaps at the same time

---

viewer/js/config/app.js
viewer/js/config/viewer.js
viewer/js/viewer/_ControllerBase.js
viewer/js/viewer/_MapMixin.js
viewer/js/viewer/_WebMapMixin.js

Adds  support for webmaps as basis for CMV application per [current specification](https://developers.arcgis.com/web-map-specification/)
* All layer types supported by webmaps are added as operational layers. [reference](https://developers.arcgis.com/web-map-specification/objects/operationalLayers/)
* basemap gallery, measure, routing (directions), and search widgets are added to CMV widgets if included in webmap. [reference](https://developers.arcgis.com/web-map-specification/objects/viewing/)
* Bookmarks included in webmap are added to bookmarks widget. [reference](https://developers.arcgis.com/web-map-specification/objects/bookmark/)
This support is intended to complement existing CMV functionality.
* Operational Layers not in the webmap can be included in CMV app configuration.
* …

Add support for webmaps

---

viewer/js/viewer/_ConfigMixin.js
viewer/js/viewer/_MapMixin.js
viewer/js/viewer/_WidgetsMixin.js

Also adds 3 new entry points within the Controller to manage when widgets can be created.
Also includes a change to uses the widget's key internally when no id is available. Some Esri widgets cannot have an id passed in the config.
1. `loading` widgets are created as early as possible - just after the config file is loaded. Example might be a [progress bar](https://github.com/thollingshead/dojo-loader-progress).
2. `layout` widgets are created after the layout is built but prior to panes being created and the map is loaded. Example: adjust the layout before any contents are added. Not sure of the usefulness of this type. Open for discussion.
3. `layer` widgets (and `map` widgets)  created after the map and layers have been loaded but prior to panes being created and before other widgets …

adds 3 new widget types: loading, layout and layer.

---

viewer/js/gis/dijit/StreetView/css/StreetView.css
viewer/js/gis/plugins/Google.js

Add position:relative to the widget's container div so the absolutely positioned button doesn't appear at the top of the page.
Allow the version of the Google API to be set in the app configuration file.

Fix StreetView Stylesheet and allow Google API version to be configured.

---

viewer/css/main.css
viewer/js/viewer/_WidgetsMixin.js

Note that this PR also includes the code from PR #643 so that PR should be reviewed and discussed first.

Add a simple loading indicator for titlePane and contentPane widgets.

---

viewer/js/gis/dijit/Identify.js

Moved the layerinfos init code into its own function `initLayerInfos` so we can call this when the topic is published that adds new layers to the layer control. 
One example of using this would be [in a custom layer generating widget](https://github.com/roemhildtg/cmv-widgets/blob/master/widgets/LabelLayer.js#L197-L212):
```javascript
layer = new FeatureLayer(serviceURL, layerOptions);
this._labelLayers[layerId] = {
layer: layer,
iconNode: this.activeLayer.iconNode
};
this.map.addLayer(layer);
// notify layer control
// wait for async layer loads
layer.on('load', lang.hitch(this, function() {
topic.publish('identify/addLayerInfos', [{
type: 'feature',
layer: layer,
title: title
}]);
}))
```
I realize this is using a layerControl topic but it makes more sense to use the existing topic than …

make identify listen for new layer contol layer adds

---

viewer/js/gis/dijit/Identify.js

Not sure I am formatting the attributes at the right place for all scenarios. Improvements or suggestions welcome. This modifies the original attributes which is a negative side effect previously noted in #650 
Also includes passing the feature geometry to the formatter. This allows for calculation of area/length/position/etc.
Example formatter for acres:
(assumes geometryEngine included in define statement)
```
acres: function (value, attributes, geometry) {
if (geometry && geometry.type === 'polygon') {
return geometryEngine.geodesicArea(geometry, 'acres');
}
return '';
},
```
Example fieldInfo:
```
{
fieldName: 'acres',
label: 'Acres',
visible: true,
format: {places: 2, digitSeparator: true},
formatter: formatters.acres
},
```
More formatter examples:
```
latlng: function (value, …
```

Enable identify formatters for feature layers.

---

viewer/js/config/viewer.js
viewer/js/gis/dijit/Legend.js

- adds new gis/dijit/Legend widget from https://github.com/cmv/cmv-app/issues/659
- fixes https://github.com/cmv/cmv-app/issues/340
- fixes https://github.com/cmv/cmv-app/issues/294

FIX: update legend when maps `update-end` event is fired

---

viewer/css/cmv-theme-overrides.css
viewer/js/config/viewer.js
viewer/js/gis/dijit/FloatingTitlePane.js
viewer/js/viewer/_WidgetsMixin.js

adds icon class as optional `iconClass` parameter in viewer.js and removes the classes from the css

Make the icons for the tilePanes configurable

---

viewer/js/gis/dijit/Identify.js

- graphics layers are identified immediately but placed in a promise to be displayed when the rest of the identifies complete.
- other layers are now identified, even though a graphic click occurred 
Related: 
- https://github.com/cmv/cmv-app/issues/521
- https://github.com/cmv/cmv-app/issues/153
Discuss:
How does this impact other identify operations?
Should this behavior be disable-able?

Override api's default graphic identify function and identify dynamic layers additionally

---

viewer/js/config/app.js
viewer/js/config/viewer.js
viewer/js/viewer/_ConfigMixin.js
viewer/js/viewer/_ControllerBase.js
viewer/js/viewer/_LayoutMixin.js
viewer/js/viewer/_MapMixin.js
viewer/js/viewer/_WebMapMixin.js
viewer/js/viewer/_WidgetsMixin.js

- make mixins less dependent on each other by implementing common methods and `this.inherited`
- `loadConfig` - a method that can load and modify the config object before the app begins loading 
- `postConfig` - a method that can initialize app variables and perform any necessary operations after the config is loaded and processed, but before startup happens
- `startup` - a method that starts the app layout, map, widgets, etc

Use inherited mixins

---

viewer/js/config/identify.js

This reverts commit 5bd6769f4366560f1b021be1e0b5ced0b04b1ec9.
This commit was merged into the wrong branch.
This will allow us to merge develop branch in preparation of version 2.0.0-beta.1 release.

Revert "Added 'draggable' property to identify config object"

---

viewer/js/viewer/_ConfigMixin.js
viewer/js/viewer/_ControllerBase.js

In `app.js` you can do something like this:
```javascript
var app = new App({
configPath: 'myConfig/path',
defaultConfig: 'explorerApp'
});
Rather than having to write a custom mixin just to change the path to the config folder.

make default config path configureable

---

viewer/js/config/identify.js
viewer/js/config/nls/main.js
viewer/js/config/viewer.js
viewer/js/gis/dijit/Identify.js

Fix bug https://github.com/cmv/cmv-app/issues/675 with better check for valid layer id

Fix dynamic layer identifies for sublayer id 0

---

viewer/js/gis/dijit/LayerControl.js
viewer/js/gis/dijit/LayerControl/controls/Graphics.js
viewer/js/gis/dijit/LayerControl/controls/OpenStreetMap.js
viewer/js/viewer/_MapMixin.js

Add support for Graphics layer as layer type and layerControl widget
Add OSM layer in layerControl widget
Remove `label` layer type since it has been deprecated by Esri.

Add support for Graphics layer (map and layerControl) and OSM layer (layerControl)

---

viewer/js/config/viewer.js
viewer/js/gis/dijit/LayerControl.js
viewer/js/gis/dijit/LayerControl/controls/Grouped.js
viewer/js/gis/dijit/LayerControl/css/LayerControl.css

* enable tri-state (indeterminate) checkbox for grouped layers
* new icons for checked/unchecked layers to support addition of tri-state
* don't group layers when there is only 1 layer in group
* don't allow reordering when grouped layers are used
* add a `getMap` function for grouped layers to avoid error with getScale
* change from `groupId` to `layerGroup`
* move layer group to `layerControllayerInfos` to avoid issue with WMS layers
* use `dojo/array`

Enhancements for grouped layers

---

viewer/js/gis/dijit/Basemaps.js
viewer/js/gis/dijit/Basemaps/css/Basemaps.css
viewer/js/gis/dijit/Basemaps/templates/Basemaps.html

Mobile friendly basemap dropdown

Add conditional css to hide basemap text on small screens

---

viewer/css/cmv-theme-overrides.css
viewer/js/config/viewer.js
viewer/js/gis/dijit/FloatingTitlePane/css/FloatingTitlePane.css
viewer/js/gis/dijit/FloatingWidgetDialog.js
viewer/js/gis/dijit/FloatingWidgetDialog/css/FloatingWidgetDialog.css
viewer/js/gis/dijit/Help.js
viewer/js/gis/dijit/Help/css/Help.css
viewer/js/gis/dijit/Help/nls/es/resource.js
viewer/js/gis/dijit/Help/nls/fr/resource.js
viewer/js/gis/dijit/Help/nls/pt-br/resource.js
viewer/js/gis/dijit/Help/nls/pt-pt/resource.js
viewer/js/gis/dijit/Help/nls/resource.js
viewer/js/viewer/_SidebarMixin.js
viewer/js/viewer/_WidgetsMixin.js
viewer/js/viewer/sidebar/Sidebar.js
viewer/js/viewer/sidebar/SidebarTab.js

Should this be the default or optional? For example, the Identify widget should probably not be delayed...

Don't load a titlePane/floating/mobile sidebar widget until the parent widget is opened.

---

viewer/js/viewer/_WidgetsMixin.js

Widget config objects require dojo classes sometimes, like `FeatureLayer` and `BasemapLayer`. `lang.clone` tries to pass the object to the constructor if it encounters these classes, which produces several issues. 
These config objects will only load if you specify a string as `options` though, I think it would be more flexible if we could pass objects with these classes in the config files directly, like `viewer.js`.

Remove `lang.clone` config from widget loader

---

viewer/js/gis/dijit/StreetView.js

since parent widget may already be open due to delayed startup
Calls the widget's layout change when the widget is started. onOpen isn't called initially otherwise because the startup is delayed.

Trigger streetview 'layoutChange' 
